version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: langchain_123
      POSTGRES_DB: langchaindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container
    ports:
      - "6024:5432"
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain

volumes:
  postgres_data: