version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: langchain_123
      POSTGRES_DB: langchaindb
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
